### ISSUE TITLE
Permanent Code ?

### ISSUE THREAD

**Issue by AT-Jerome** [acvetkov/chrome-store-api#4]
Hello,

It seems that the code can be used only one time.

I don't find another solution to get this code than using the browser with the clientId. 

Is it possible to get a permanent code, or an api which can return this code directly (without confirmation) ?

Best regards

**Comment by acvetkov** [comment]
@AT-Jerome Hi.

Unfortunately, there is no way to solve your problem.
Read official doc.
https://developer.chrome.com/webstore/using_webstore_api

**Comment by AT-Jerome** [comment]
Hi,

yes I've read this doc and I was hoping that there is another solution...

thanks for this answer and your work,

Regards

**Comment by acvetkov** [comment]
@AT-Jerome you are welcome
